[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "super-jax"
authors = [{name = "Kyle", email = "kmill@lle.rochester.edu"}]
dynamic = ["version", "description"]
